name: flutter_inherited_model
description: "This package provides an easy way to use InheritedModel with code generation. It helps optimize app performance by rebuilding only the necessary widgets when the state changes."
version: 0.9.5
homepage: https://github.com/zpdL-Studio/flutter_inherited_model_by_zpdl/tree/main/flutter_inherited_model

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
