name: flutter_inherited_model_builder
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter_inherited_model:
    path: ../flutter_inherited_model
  analyzer: ^7.0.0
  build: ^2.0.0
  source_gen: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
