name: flutter_inherited_model_builder
description: "Flutter inherited model builder"
version: 0.9.1
homepage: https://github.com/zpdL-Studio/flutter_inherited_model_by_zpdl/tree/main/flutter_inherited_model_builder

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter_inherited_model: ^0.9.1

  analyzer: ^7.0.0
  build: ^2.0.0
  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
