name: example
description: "flutter inherited model example"
publish_to: 'none'

version: 0.9.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_inherited_model: ^0.9.1
#  flutter_inherited_model:
#    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_inherited_model_builder: ^0.9.1
#  flutter_inherited_model_builder:
#    path: ../../flutter_inherited_model_builder

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
flutter:
  uses-material-design: true
